services:
  bentopdf:
    image: ghcr.io/alam00000/bentopdf:latest
    container_name: bentopdf
    deploy:
      resources:
        limits:
          cpus: ${CPU}
          memory: ${MEMORY}
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - private
    restart: unless-stopped


# Networks public / private if not attached to host
networks:
  private:
    name: ${APP_NAME}-private
    internal: true
