services:
  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped
    container_name: prometheus
    user: ${UID:-1000}:${GID:-1000}
    networks:
      - unpoller-network
    environment:
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    container_name: grafana
    user: ${UID:-1000}:${GID:-1000}
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=${GF_USERS_ALLOW_SIGN_UP}
      - GF_PLUGINS_PREINSTALL=${GF_PLUGINS_PREINSTALL}
      - TZ=${TZ}
      - UID=${UID}
      - GID=${GID}
    networks:
      - unpoller-network
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    depends_on:
      - prometheus

  unpoller:
    image: ghcr.io/unpoller/unpoller:latest
    container_name: unpoller
    restart: unless-stopped
    networks:
      - unpoller-network
    environment:
      - UP_INFLUXDB_DISABLE=${UP_INFLUXDB_DISABLE}
      - UP_POLLER_DEBUG=${UP_POLLER_DEBUG}
      - UP_UNIFI_DYNAMIC=${UP_UNIFI_DYNAMIC}
      - UP_PROMETHEUS_HTTP_LISTEN=${UP_PROMETHEUS_HTTP_LISTEN}
      - UP_PROMETHEUS_NAMESPACE=${UP_PROMETHEUS_NAMESPACE}
      - UP_UNIFI_CONTROLLER_0_VERIFY_SSL=${UP_UNIFI_CONTROLLER_0_VERIFY_SSL}
      - UP_UNIFI_CONTROLLER_0_SAVE_ALARMS=${UP_UNIFI_CONTROLLER_0_SAVE_ALARMS}
      - UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES=${UP_UNIFI_CONTROLLER_0_SAVE_ANOMALIES}
      - UP_UNIFI_CONTROLLER_0_SAVE_EVENTS=${UP_UNIFI_CONTROLLER_0_SAVE_EVENTS}
      - UP_UNIFI_CONTROLLER_0_SAVE_IDS=${UP_UNIFI_CONTROLLER_0_SAVE_IDS}
      - UP_UNIFI_CONTROLLER_0_SAVE_SITES=${UP_UNIFI_CONTROLLER_0_SAVE_SITES}
      - UP_UNIFI_CONTROLLER_0_SAVE_DPI=${UP_UNIFI_CONTROLLER_0_SAVE_DPI}
      - UP_UNIFI_CONTROLLER_0_URL=${UP_UNIFI_CONTROLLER_0_URL}
      - UP_UNIFI_CONTROLLER_0_USER=${UP_UNIFI_CONTROLLER_0_USER}
      - UP_UNIFI_CONTROLLER_0_PASS=${UP_UNIFI_CONTROLLER_0_PASS}
      - UP_UNIFI_CONTROLLER_0_SITE=${UP_UNIFI_CONTROLLER_0_SITE}

networks:
  unpoller-network:
    name: unpoller-network
    external: false